 
# replicate 5 5 5  
# molecule water molecule.water
 mass 71 2.016
# create_atoms 0 random 2887 12495 NULL mol water 12348 
 group water type 70 71
 group gly subtract all water

 delete_atoms group gly
 
 timestep 1.0
 fix wt water shake 0.0001 20 0 b 254 a 155
 pair_modify mix geometric  
 #fix ens all nve
 fix ens all npt temp 328 328 100 iso 1 1 1000
 #minimize 1e-5 1e-5 10000 10000 
 run 1000000
 write_data data.4
